"""ZenML archive ETL pipeline.

Windows note
------------
The Windows local artifact store cannot create directories containing ':'.
Some ZenML dynamic-map invocation IDs are formatted like
``map:process_archive_page:0``. Therefore this project intentionally does
not use ``step.map()`` with the default Windows local orchestrator.

Instead, the dynamic pipeline materializes the small list of archive page
URLs and creates one normal ``process_archive_page`` step per page. This
keeps the requested page-as-batch architecture while avoiding the Windows
path bug. On Linux/remote orchestration, map-based parallelism can be added
later with a dedicated production stack.
"""

from __future__ import annotations

from zenml import pipeline
from zenml.logger import get_logger

from steps.initialize_database import initialize_database
from steps.load_urls import load_urls
from steps.process_archive_page import process_archive_page

logger = get_logger(__name__)


@pipeline(dynamic=True, enable_cache=True)
def archive_data_etl(
    first_page: bool = False,
    domain: str = "all",
) -> None:
    """Run one page-level ETL batch for every selected archive page.

    Each page is treated as a single batch and ``process_archive_page``
    extracts at most 20 article candidates from that page. The page step
    performs application-level deduplication, scraping, validation,
    PostgreSQL persistence and Parquet bronze writing.

    ``load_urls`` is cacheable because it deterministically generates archive
    page URLs. The database and scraping steps are not cacheable because they
    depend on runtime database state and external web content.

    The sequential dynamic fan-out used here is intentional for Windows with
    the local ZenML orchestrator. It avoids illegal Windows artifact-store
    paths generated by mapped step invocation IDs.
    """
    db_ready = initialize_database()
    page_urls = load_urls(domain=domain, first_page=first_page)

    # ``load()`` is used here deliberately: the list is small (max 2,500
    # URLs for the current five domains), and we need the concrete page URLs
    # to create the dynamic page-level steps. We do NOT load article content.
    pages = page_urls.load()

    logger.info(
        "dynamic_page_batches_created domain=%s first_page=%s page_count=%d",
        domain,
        first_page,
        len(pages),
    )

    for page_url in pages:
        process_archive_page(
            page_url=page_url,
            database_ready=db_ready,
        )
